### ISSUE TITLE
UI: Store for SteamDeck

### ISSUE THREAD

**Issue by pimentel08** [HyperPlay-Gaming/hyperplay-desktop-client#116]

**Comment by jacobc-eth** [comment]
What should we do with this card?  The store is looking pretty good on steamdeck, but I think the challenge is it isn't controller navigable.

**Comment by biliesilva** [comment]
We are reorganizing our components to fit better in the SteamDeck screen, focusing more on usability and bringing more of the Steam feel related to navigation. It includes all stores too.

**Comment by biliesilva** [comment]
I tried to adjust here as much as I could with the components we already have so that it doesn't all stick together. Resized some (game picture for example).
![SteamDeck-Store.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/c9d0d08d-a289-452d-86f6-12fd991b9d4a)
![SteamDeck-HyperPlay-gameStore.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/172e3098-2001-49a7-a974-daa54c75b4ec)

**Comment by biliesilva** [comment]
The current navigation is impaired and a large part of the Store is cut off due to the size of the banner.

**Comment by iamdavid0091** [comment]
This is captured in this [Avion story](https://game7.avion.io/map/3zsNCKL4j7Ej9eGNY/zvcxKAoiZPLzjRn2A)
