### ISSUE TITLE
Setup Translation Server

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#137]

**Comment by wswarren12** [comment]
@jacobc-eth -- just want to confirm that Translation Server in this context is for language localization before I start grooming.

**Comment by flavioislima** [comment]
We will use Weblate since it is open-source and will be hosted on their servers.
the project will be public for anyone to translate
A review process will be needed for all languages
We will still review It again on Github when Weblate pushes the PR to our repo.
Investigate if it is possible to have the project name private and only the strings as public to have extra protection.
