### ISSUE TITLE
Find instructions for installing on a steamdeck

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#273]
As a player on SteamDeck unfamiliar with sideloading apps, I'd like to see instruction for installing on SteamDeck when selecting the SteamDeck option from the downloads pages, so that I understand how to install HyperPlay.

**Description**

This is adjustments to the download page to display installation instructions when installing.

As a part of this design, we should revisit the number of items on the download page and how we can consolidate and improve the UI.

**Comment by jacobc-eth** [comment]
Example tutorial: https://discord.com/channels/1001783401608663240/1049370816866963517/1097590180707324066

**Comment by Kwilke1982** [comment]
To install HyperPlay on your SteamDeck, follow these steps:

1. Open the SteamDeck's Desktop Mode by pressing the power button for approximately 2 seconds to open the context menu. Then, select **"Switch to Desktop"**
2. Navigate to https://www.HyperPlay.xyz in your web browser
3. Click on the **"Download"** button, and then select "**SteamDeck"**
4. Choose **"Install"** to begin the installation process

Instead of navigating to the HyperPlay website, you can also find HyperPlay in the Discover Store and install it from there.

Once you have installed HyperPlay, you may want to make it appear within the main context menu of the SteamDeck. To do this, open Steam in Desktop Mode, go to **"Library"**, and then click "**Add a Game"**. Select **"HyperPlay"** from the list of installed games.

Congratulations! You have successfully installed and added HyperPlay to your SteamDeck. It is now available to use in Steam's gaming mode.

**Comment by biliesilva** [comment]
Adding a button for SteamDeck makes more sense after reading the tutorials you guys suggested. But I don't know if makes sense adding this tutorial on the download menu (website)
![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/3f28e158-58f4-4e92-ba8a-28a210961d86)

**Comment by flavioislima** [comment]
The instructions are not correct because we do not need to go to the HP page to download on the SteamDeck, it can be downloaded from the official App Store for it called Discover.

So the correct instructions would be:

- Open the SteamDeck's Desktop Mode by pressing the power button for approximately 2 seconds to open the context menu. Then, select "Switch to Desktop"
- Search and open the Discover App store.
- On Discover, search for HyperPlay
- Click Install
- Enjoy ;)

**Comment by biliesilva** [comment]
Here a suggested flow: ![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/376102e2-bfbd-42d7-885c-c348d490358d)

**Comment by flavioislima** [comment]
@biliesilva 

For Windows: No need, we can keep it as it is for now. If we start to support ARM64 Windows then we can get back to it.

For macOS: 
Two buttons: One for Intel Chips and another for Apple Chips (M1/M2). I don't think more explanation is needed for that.

For Linux (5 buttons):
- Linux App Store (Discover, Gnome Store, etc) (Recommended): HyperPlay is available on all major distributions through Flatpak and Snap. That includes distros like Ubuntu, Pop!OS, OpenSuse, Arch Linux, ZorinOS, and a lot more. If you cannot find it on the App Store, _click here to setup Flatpak on your Linux Distro_. (Should contain a link to the Flathub Page).
- .deb: For distros based on Debian and Ubuntu, download the Deb file and double-click to install it or type on the terminal: `sudo dpkg -i hyperplay_*_amd64.deb`.
- .rpm: For Fedora, Nobara, Red Hat and derivatives. Download here the Deb file and double-click to install it or type on the terminal: `sudo dnf install ./hyperplay-*.x86_64.rpm` 
- Tar.xz: Generic build that will work on almost any distribution. Just download, extract, make the hyperplay binary executable and double-click to run it. 
- AUR; If you use Arch Linux or any distro derivative from it like Manjaro, Elementary and Garuda. You can install search and install HyperPlay from the AUR. Just make sure AUR is enabled and then install it from package managers like Pamac or similar. The name of the official package is `hyperplay`


 I think we should discuss about not distributing DEBs and RPMs in the future and push Flatpak instead (or SNAP). Let's keep it like this for now and discuss that in the future.

**Comment by biliesilva** [comment]
![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/a8076c84-df67-4a8d-ac90-45f526196d79)

**Comment by biliesilva** [comment]
The idea for Linux is this one, but trying to work in a better way to visualize it: ![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/b666390d-db9d-4e5a-a8dd-ce36e01fe469)

**Comment by biliesilva** [comment]
Mac, as Flavio said, doesn't need a tutorial: 

![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/bff63458-9936-46d2-bf4c-80574eee236c)

**Comment by flavioislima** [comment]
For the Flathub (flatpak) we can use the logo from their website:

```<svg height="24" width="88" version="1.1" viewBox="0 0 219 59.106" xmlns="http://www.w3.org/2000/svg" fill="currentColor"><g transform="matrix(.89089 0 0 .89089 -2448.3 -532.77)" stroke-width="1.1225"><g transform="matrix(1.7388 0 0 1.7388 2471.7 448.13)" stroke-width="2.4398"></g><g transform="matrix(1.7622 0 0 1.7622 2470.4 445.42)"><circle cx="166.69" cy="95.647" r="9.0478" stroke-width=".63698"></circle><rect x="158.75" y="108.33" width="15.875" height="15.875" rx="4.2333" ry="4.2333" stroke-width=".63698"></rect><path transform="matrix(.91132 .52615 .52615 -.91132 101.23 110.53)" d="m69.514 58.833h-1.7806-10.247a2.4441 2.4441 60 0 1-2.1167-3.6662l6.0139-10.416a2.4441 2.4441 2.522e-7 0 1 4.2333 0l6.0139 10.416a2.4441 2.4441 120 0 1-2.1167 3.6662z" stroke-width=".60953"></path><path transform="rotate(90)" d="m116.31-194.99c0.87946 0 1.5875 0.70801 1.5875 1.5875v12.7c0 0.87946-0.70802 1.5875-1.5875 1.5875s-1.5875-0.70802-1.5875-1.5875v-12.7c0-0.87946 0.70801-1.5875 1.5875-1.5875zm-7.9375 7.9375c0-0.87946 0.70802-1.5875 1.5875-1.5875h12.7c0.87946 0 1.5875 0.70802 1.5875 1.5875 0 0.87947-0.70802 1.5875-1.5875 1.5875h-12.7c-0.87947 0-1.5875-0.70802-1.5875-1.5875z" stroke-width="6.3698"></path></g></g></svg>```

Or:
![image](https://user-images.githubusercontent.com/26871415/236400522-47e198c6-57b6-4dd2-a0b7-1fb0056c462e.png)

For .deb, debian logo:
![image](https://user-images.githubusercontent.com/26871415/236400036-2349c398-44ab-4528-a4b8-496a8b878bbb.png)

For SnapStore, ubuntu logo:
![image](https://user-images.githubusercontent.com/26871415/236400141-47368764-07a6-4396-8127-c45ca9442454.png)

For AUR, Arch Linux logo:
![image](https://user-images.githubusercontent.com/26871415/236400282-fe2510d8-c029-4479-96ae-7805b21ba9a8.png)

For Tar.xz we can keep the Linux logo since its universal.

Those logos are examples, we should try to find some SVGs for them as well

**Comment by flavioislima** [comment]
Working on cleaning up the downloads page, I am almost done with it but so far this is how its going:

![telegram-cloud-photo-size-1-5176976471783221916-y.jpg](https://images.zenhubusercontent.com/6307c38ff85d6020fea07f59/bd011df5-c202-4c7c-9d5f-d0e945d591e6)
![telegram-cloud-photo-size-1-5176976471783221915-y.jpg](https://images.zenhubusercontent.com/6307c38ff85d6020fea07f59/57de09fd-d7e0-4224-ac46-69889a5fea3e)
![telegram-cloud-photo-size-1-5176976471783221913-y.jpg](https://images.zenhubusercontent.com/6307c38ff85d6020fea07f59/ff7695a4-675e-48c0-bf81-81a0b0103a22)
![telegram-cloud-photo-size-1-5176976471783221914-y.jpg](https://images.zenhubusercontent.com/6307c38ff85d6020fea07f59/70d7e15f-1030-4127-a1ca-31df0887b4e1)

**Comment by flavioislima** [comment]
Forget it, I am blind. I found the icon on the Figma file.

**Comment by flavioislima** [comment]
Ok, update the cons with the new ones now I think it's done:

![image.png](https://images.zenhubusercontent.com/6307c38ff85d6020fea07f59/8bf17fc7-6ce8-48af-84b7-c2b7db295f7b)

![image.png](https://images.zenhubusercontent.com/6307c38ff85d6020fea07f59/203b1c9f-3e4a-47d5-92b7-04c1eaa01b4e)
